### ISSUE TITLE
代码优化建议

### ISSUE THREAD

**Issue by LewisGu** [icomgx/bilibili-rank-spider#1]
clone并本地搭建环境大致看了一下，目前有几个建议：0x00.在主要操作之间加入打印语句以方便调试，不然代码量以后越来越大，可能调试就越来越不便捷了；0x01.password这种敏感信息最好还是通过input输入为好；0x02.本质上这也是一种爬虫，是否考虑可以构建不同的头\代理池来进行多次爬取【虽然现在确实没有什么必要】
我也是新手小白，还是感谢提供这样的代码供使用学习【鞠躬】

**Comment by icomgx** [comment]
非常感谢您的建议，因为数据体量不大计划改用Sqlite数据库所以密码的问题就可以解决了，代理池暂时没有必要使用因为频率很低1次/天，我也是刚开始接触多多交流互相学习，再次感谢您的建议。
